# ITC21(Modeling & Simulation )

## Implementaion of Basic Programs in Python

### Name : Shreshth
### RollNo : 2018UIT2528

In [1]:
# Question 1: Generate vector of 10 random integers between
# -50 to +50
import numpy as np
vector = np.random.randint(-50,50,size=10)
vector

array([-48, -12,  42,   3, -33,  29, -25,   5,   3, -15])

In [2]:
# Question 2: Program to get First 10 Fibonacci Numbers
import numpy as np
n = 10
fib = np.zeros(n,dtype=int)
for i in range(1,n):
    if(i==1):
        fib[i] = 1
    else:
        fib[i] = fib[i-1] + fib[i-2]
fib

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34])

In [3]:
# Question 3: Program to print No. from 1 to100 and print 'Fizz' 
# for multiples of 3, "Buzz" for multiples of 5, "FizzBuzz" for
# multiples of both
for i in range(1,101):
    if(i%3==0 and i%5==0):
        print(i,'FizzBuzz')
    elif(i%3==0):
        print(i,'Fizz')
    elif(i%5==0):
        print(i,'Buzz')
    else:
        print(i)

1
2
3 Fizz
4
5 Buzz
6 Fizz
7
8
9 Fizz
10 Buzz
11
12 Fizz
13
14
15 FizzBuzz
16
17
18 Fizz
19
20 Buzz
21 Fizz
22
23
24 Fizz
25 Buzz
26
27 Fizz
28
29
30 FizzBuzz
31
32
33 Fizz
34
35 Buzz
36 Fizz
37
38
39 Fizz
40 Buzz
41
42 Fizz
43
44
45 FizzBuzz
46
47
48 Fizz
49
50 Buzz
51 Fizz
52
53
54 Fizz
55 Buzz
56
57 Fizz
58
59
60 FizzBuzz
61
62
63 Fizz
64
65 Buzz
66 Fizz
67
68
69 Fizz
70 Buzz
71
72 Fizz
73
74
75 FizzBuzz
76
77
78 Fizz
79
80 Buzz
81 Fizz
82
83
84 Fizz
85 Buzz
86
87 Fizz
88
89
90 FizzBuzz
91
92
93 Fizz
94
95 Buzz
96 Fizz
97
98
99 Fizz
100 Buzz


In [4]:
# Question 4: Program to create a blank matrix of shape 5,5
import numpy as np
blank = np.zeros((5,5),dtype=int)
blank

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
# Question 5: Program to create a matrix taking a given vector of
# no. as input and define the column and row names. Display the
# matrix
import numpy as np
import pandas as pd
col1 = np.arange(0,5)
col2 = np.arange(5,10)
col3 = np.arange(10,15)

matrix = pd.DataFrame({'Col1':col1,
                       'Col2':col2,
                       'Col3':col3},
                        index=['Row1','Row2','Row3','Row4','Row5'])
matrix

Col1  Col2  Col3
Row1     0     5    10
Row2     1     6    11
Row3     2     7    12
Row4     3     8    13
Row5     4     9    14